apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: openvpn
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openvpn
  ports:
    - protocol: UDP
      port: 1194
      targetPort: 1194
      name: openvpn-udp
      nodePort: 31194
    - protocol: TCP
      port: 1194
      targetPort: 1194
      name: openvpn-tcp
      nodePort: 31194
