{{- if .Values.openvpn.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "openvpn-router.fullname" .) .Values.openvpn.secretName }}
  labels:
    {{- include "openvpn-router.labels" . | nindent 4 }}
type: Opaque
stringData:
  tls.crt: {{ .Values.openvpn.secret.tlsCrt | quote }}
  tls.key: {{ .Values.openvpn.secret.tlsKey | quote }}
  {{- if .Values.openvpn.crypto.tlsCrypt }}
  tls-crypt.pem: {{ required "openvpn.secret.tlsCryptPem is required when openvpn.secret.create=true and openvpn.crypto.tlsCrypt=true" .Values.openvpn.secret.tlsCryptPem | quote }}
  {{- end }}
  {{- if .Values.openvpn.secret.ovpnLoginToml }}
  ovpn_login.toml: {{ .Values.openvpn.secret.ovpnLoginToml | quote }}
  {{- else }}
  ovpn_login.toml: |-
    [database]
    user = {{ .Values.openvpn.loginConfig.database.user | quote }}
    password = {{ .Values.openvpn.loginConfig.database.password | quote }}
    dbname = {{ .Values.openvpn.loginConfig.database.dbname | quote }}
    host = {{ .Values.openvpn.loginConfig.database.host | quote }}
    sslmode = {{ .Values.openvpn.loginConfig.database.sslmode | quote }}
    port = {{ .Values.openvpn.loginConfig.database.port | quote }}
    table = {{ .Values.openvpn.loginConfig.database.table | quote }}
  {{- end }}
{{- end }}
