name: Unstable Release

on:
  push:
    # Pattern matched against refs/tags
    branches:
      - master
  schedule:
    - cron: "0 10 * * *"

jobs:
  build-ovpn_login:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K8S_IMAGE: docker.io/alpine/k8s:1.36.2
      ALPINE_IMAGE: docker.io/library/alpine:3.24.1
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Build ovpn_login
      run: |
        podman pull golang:alpine
        podman pull $K8S_IMAGE
        podman pull $ALPINE_IMAGE
        podman build -f Dockerfile --build-arg BUILD=${{ env.SHORT_SHA }} --build-arg K8S_IMAGE=$K8S_IMAGE --build-arg ALPINE_IMAGE=$ALPINE_IMAGE . --target=app \
                     -t docker.io/pcm0/openvpn:${{ env.SHORT_SHA }}
        podman build -f Dockerfile --build-arg BUILD=${{ env.SHORT_SHA }} --build-arg K8S_IMAGE=$K8S_IMAGE --build-arg ALPINE_IMAGE=$ALPINE_IMAGE . --target=slim \
                     -t docker.io/pcm0/openvpn:slim-${{ env.SHORT_SHA }}
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
    - name: Docker System Prune
      run: |
        podman system prune --force --all
